-- ====================================================================
-- KHANI Fashion - Schéma PostgreSQL (Supabase)
-- Adapté de database/schema.sql (MySQL) pour la migration vers Supabase.
-- Exécuté automatiquement par database/migrate_to_supabase.php
-- ou via l'éditeur SQL de Supabase.
--
-- Notes de conversion MySQL → PostgreSQL :
--   AUTO_INCREMENT        → GENERATED BY DEFAULT AS IDENTITY
--   ENUM(...)             → VARCHAR + contrainte CHECK
--   TINYINT(1)            → SMALLINT + CHECK (0/1)
--   DATETIME              → TIMESTAMP
--   ON UPDATE CURRENT_TIMESTAMP → trigger set_updated_at()
--   INDEX dans CREATE TABLE → CREATE INDEX séparés
-- ====================================================================

-- --------------------------------------------------------------------
-- Table : admin
-- Stocke les comptes administrateurs (mot de passe hashé bcrypt)
-- --------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS admin (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    nom_complet VARCHAR(100),
    email VARCHAR(150),
    role VARCHAR(20) NOT NULL DEFAULT 'admin' CHECK (role IN ('superadmin','admin')),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- --------------------------------------------------------------------
-- Table : categories
-- --------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS categories (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom VARCHAR(100) NOT NULL UNIQUE,
    image VARCHAR(255),
    description TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- --------------------------------------------------------------------
-- Table : produits
-- --------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS produits (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom VARCHAR(200) NOT NULL,
    description TEXT,
    prix DECIMAL(10,2) NOT NULL,
    image VARCHAR(255),
    categorie_id INT REFERENCES categories(id) ON DELETE SET NULL,
    stock INT DEFAULT 0,
    actif SMALLINT NOT NULL DEFAULT 1 CHECK (actif IN (0,1)),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_categorie ON produits (categorie_id);
CREATE INDEX IF NOT EXISTS idx_actif ON produits (actif);

-- --------------------------------------------------------------------
-- Table : commandes
-- --------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS commandes (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reference VARCHAR(20) NOT NULL UNIQUE,
    client_nom VARCHAR(150) NOT NULL,
    client_telephone VARCHAR(30) NOT NULL,
    client_email VARCHAR(150),
    client_adresse TEXT,
    ville VARCHAR(100),
    mode_paiement VARCHAR(20) NOT NULL DEFAULT 'livraison'
        CHECK (mode_paiement IN ('livraison','mobile_money','carte')),
    produits_json JSON NOT NULL,
    total DECIMAL(10,2) NOT NULL,
    statut VARCHAR(20) NOT NULL DEFAULT 'en_attente'
        CHECK (statut IN ('en_attente','confirmee','en_livraison','livree','annulee')),
    notes TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_statut ON commandes (statut);
CREATE INDEX IF NOT EXISTS idx_date ON commandes (created_at);

-- --------------------------------------------------------------------
-- Table : parametres (stockage clé/valeur pour les infos boutique)
-- --------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS parametres (
    cle VARCHAR(50) PRIMARY KEY,
    valeur TEXT,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- --------------------------------------------------------------------
-- Table : visiteurs (compteur)
-- --------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS visiteurs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ip VARCHAR(45),
    page VARCHAR(100),
    user_agent TEXT,
    visited_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_visiteurs_date ON visiteurs (visited_at);

-- --------------------------------------------------------------------
-- Mise à jour automatique de updated_at
-- (équivalent PostgreSQL de ON UPDATE CURRENT_TIMESTAMP de MySQL)
-- --------------------------------------------------------------------
CREATE OR REPLACE FUNCTION set_updated_at() RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_produits_updated_at ON produits;
CREATE TRIGGER trg_produits_updated_at
    BEFORE UPDATE ON produits
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_commandes_updated_at ON commandes;
CREATE TRIGGER trg_commandes_updated_at
    BEFORE UPDATE ON commandes
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_parametres_updated_at ON parametres;
CREATE TRIGGER trg_parametres_updated_at
    BEFORE UPDATE ON parametres
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();
